insert into sb_test_item (id, description) values(1,'Vizca');
insert into sb_test_item (id, description) values(2,'Barca');
insert into sb_test_item (id, description) values(3,'El Barcelona se consagró');
insert into sb_test_item (id, description) values(4,'campeón de La Liga');
insert into sb_test_item (id, description) values(5,'este domingo al vencer');
insert into sb_test_item (id, description) values(6,'4-2 al Deportivo La');
insert into sb_test_item (id, description) values(7,'Coruña como visitante en');
insert into sb_test_item (id, description) values(8,'un torneo');
insert into sb_test_item (id, description) values(9,'en');
insert into sb_test_item (id, description) values(10,'el');
insert into sb_test_item (id, description) values(11,'que puede hacer historia');
insert into sb_test_item (id, description) values(12,'más allá del título.');
insert into sb_test_item (id, description) values(13,'Es que si en las tres');
insert into sb_test_item (id, description) values(14,'próximas fechas no pierde');
insert into sb_test_item (id, description) values(15,'los dirigidos por Ernesto');
insert into sb_test_item (id, description) values(16,'Valverde serán los');
insert into sb_test_item (id, description) values(17,'primeros en ganar');
insert into sb_test_item (id, description) values(18,'el torneo invictos.');
insert into sb_test_item (id, description) values(19,'La gran figura de esta');
insert into sb_test_item (id, description) values(20,'temporada volvió a ser');
insert into sb_test_item (id, description) values(21,'Lionel Messi');
