server:
  port: 8080
  servlet:
    context-path: /sbtest

# Enabling H2 Console
spring:
  h2.console.enabled: true

mybatis:
  typeAliasesPackage: ar.com.tuchorc.persistence.model
  configuration:
    map-underscore-to-camel-case: true
    jdbcTypeForNull: VARCHAR

logging:
  level:
    org.springframework: INFO
    ar.com.tuchorc: INFO
    ar.com.tuchorc.persistence.mappers: DEBUG