server:
  port: 8080
  contextPath: /sbtest

# Enabling H2 Console
spring:
  h2.console.enabled: true
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework: INFO
    ar.com.tuchorc: INFO
    ar.com.tuchorc.persistence.mappers: DEBUG

sbtest:
  oauth:
    tokenTimeout: 3600
